const allProducts = {
    // Main Products (Categories)
    'bed': { name: 'سرویس خواب', image: 'images/bed.jpg', type: 'دسته بندی', link: 'bed.html' },
    'tv': { name: 'میز تلویزیون', image: 'images/tv.jpg', type: 'دسته بندی', link: 'tv.html' },
    'mirror': { name: 'آینه کنسول', image: 'images/mirror.jpg', type: 'دسته بندی', link: 'mirror.html' },
    'jak': { name: 'جاکفشی', image: 'images/jak.jpg', type: 'دسته بندی', link: 'jak.html' },
    'sofa': { name: 'جلو مبلی', image: 'images/sofa.jpg', type: 'دسته بندی', link: 'sofa.html' },
    'deco': { name: 'محصولات تزیینی', image: 'images/deco.jpg', type: 'دسته بندی', link: 'deco.html' },
    'sofaes': { name: 'مبل استیل', image: 'images/sofaes.jpg', type: 'دسته بندی', link: 'sofaes.html' },
    'ayne': { name: 'آیینه قدی', image: 'images/ayne.jpg', type: 'دسته بندی', link: 'ayne.html' },
    'safar': { name: 'مبل راحتی', image: 'images/safar.jpg', type: 'دسته بندی', link: 'sofar.html' },

    'bednojavan': { name: 'سرویس خواب تک نفره (نوجوان)', image: 'images/bednojavan.jpg', type: 'دسته بندی', link: 'bednojavan.html' },
    'jahaz': { name: 'جهیزیه', image: 'images/jahaz.jpg', type: 'دسته بندی', link: 'jahaz.html' },
    'tablo': { name: 'اکسسوری و تابلو', image: 'images/tablo.jpg', type: 'دسته بندی', link: 'tablo.html' },
    'bar': { name: 'بار قهوه', image: 'images/bar.jpg', type: 'دسته بندی', link: 'bar.html' },
 
    // Bed Products
    'bed1': { id: 'bed1', name: 'سرویس خواب کلاسیک', type: 'چوب راش', image: 'images/bed1.jpg' },
    'bed2': { id: 'bed2', name: 'سرویس خواب مدرن', type: 'چوب گردو', image: 'images/bed2.jpg' },
    'bed3': { id: 'bed3', name: 'سرویس خواب سلطنتی', type: 'چوب بلوط', image: 'images/bed3.jpg' },
    'bed4': { id: 'bed4', name: 'سرویس خواب مینیمال', type: 'چوب کاج', image: 'images/bed4.jpg' },
    'bed5': { id: 'bed5', name: 'سرویس خواب کودک', type: 'چوب توت', image: 'images/bed5.jpg' },
    'bed6': { id: 'bed6', name: 'سرویس خواب لوکس', type: 'چوب ممرز', image: 'images/bed6.jpg' },
    'bed7': { id: 'bed7', name: 'سرویس خواب جدید ۱', type: 'چوب', image: 'images/bed7.jpg' },
    'bed8': { id: 'bed8', name: 'سرویس خواب جدید ۲', type: 'چوب', image: 'images/bed8.jpg' },
    'bed9': { id: 'bed9', name: 'سرویس خواب جدید ۳', type: 'چوب', image: 'images/bed9.jpg' },
    'bed10': { id: 'bed10', name: 'سرویس خواب جدید ۴', type: 'چوب', image: 'images/bed10.jpg' },
    'bed11': { id: 'bed11', name: 'سرویس خواب جدید ۵', type: 'چوب', image: 'images/bed11.jpg' },
    'bed12': { id: 'bed12', name: 'سرویس خواب جدید ۶', type: 'چوب', image: 'images/bed12.jpg' },
    'bed13': { id: 'bed13', name: 'سرویس خواب جدید ۷', type: 'چوب', image: 'images/bed13.jpg' },
    'bed14': { id: 'bed14', name: 'سرویس خواب جدید ۸', type: 'چوب', image: 'images/bed14.jpg' },
    'bed15': { id: 'bed15', name: 'سرویس خواب جدید ۹', type: 'چوب', image: 'images/bed15.jpg' },
    'bed16': { id: 'bed16', name: 'سرویس خواب جدید ۱۰', type: 'چوب', image: 'images/bed16.jpg' },
    'bed17': { id: 'bed17', name: 'سرویس خواب جدید ۱۱', type: 'چوب', image: 'images/bed17.jpg' },
    'bed18': { id: 'bed18', name: 'سرویس خواب جدید ۱۲', type: 'چوب', image: 'images/bed18.jpg' },
    'bed19': { id: 'bed19', name: 'سرویس خواب جدید ۱۳', type: 'چوب', image: 'images/bed19.jpg' },
    'bed20': { id: 'bed20', name: 'سرویس خواب جدید ۱۴', type: 'چوب', image: 'images/bed20.jpg' },
    'bed21': { id: 'bed21', name: 'سرویس خواب جدید ۱۵', type: 'چوب', image: 'images/bed21.jpg' },

    // Bed Nojavan Products
    'bednojavan1': { id: 'bednojavan1', name: 'سرویس خواب نوجوان مدل A', type: 'چوب راش', image: 'images/bednojavan1.jpg' },
    'bednojavan2': { id: 'bednojavan2', name: 'سرویس خواب نوجوان مدل B', type: 'چوب گردو', image: 'images/bednojavan2.jpg' },
    'bednojavan3': { id: 'bednojavan3', name: 'سرویس خواب نوجوان مدل C', type: 'چوب بلوط', image: 'images/bednojavan3.jpg' },
    'bednojavan4': { id: 'bednojavan4', name: 'سرویس خواب نوجوان مدل D', type: 'چوب کاج', image: 'images/bednojavan4.jpg' },
    'bednojavan5': { id: 'bednojavan5', name: 'سرویس خواب نوجوان مدل E', type: 'چوب توت', image: 'images/bednojavan5.jpg' },
    'bednojavan6': { id: 'bednojavan6', name: 'سرویس خواب نوجوان مدل F', type: 'چوب ممرز', image: 'images/bednojavan6.jpg' },

    // Jahaz Products
    'jahaz1': { id: 'jahaz1', name: 'پکیج جهیزیه کامل A', type: 'اقتصادی', image: 'images/jahaz1.jpg' },
    'jahaz2': { id: 'jahaz2', name: 'پکیج جهیزیه کامل B', type: 'استاندارد', image: 'images/jahaz2.jpg' },
    'jahaz3': { id: 'jahaz3', name: 'پکیج جهیزیه کامل C', type: 'لوکس', image: 'images/jahaz3.jpg' },
    'jahaz4': { id: 'jahaz4', name: 'پکیج جهیزیه کامل D', type: 'سلطنتی', image: 'images/jahaz4.jpg' },
    'jahaz5': { id: 'jahaz5', name: 'پکیج جهیزیه کامل E', type: 'مدرن', image: 'images/jahaz5.jpg' },
    'jahaz6': { id: 'jahaz6', name: 'پکیج جهیزیه کامل F', type: 'کلاسیک', image: 'images/jahaz6.jpg' },
    
    // TV Stand Products (Assuming similar structure)
    'tv1': { id: 'tv1', name: 'میز تلویزیون مدل A', type: 'چوب راش', image: 'images/tv1.jpg' },
    'tv2': { id: 'tv2', name: 'میز تلویزیون مدل B', type: 'چوب گردو', image: 'images/tv2.jpg' },
    'tv3': { id: 'tv3', name: 'میز تلویزیون مدل C', type: 'چوب بلوط', image: 'images/tv3.jpg' },
    'tv4': { id: 'tv4', name: 'میز تلویزیون مدل D', type: 'چوب', image: 'images/tv4.jpg' },
    'tv5': { id: 'tv5', name: 'میز تلویزیون مدل E', type: 'چوب', image: 'images/tv5.jpg' },
    'tv6': { id: 'tv6', name: 'میز تلویزیون مدل F', type: 'چوب', image: 'images/tv6.jpg' },
    'tv7': { id: 'tv7', name: 'میز تلویزیون مدل G', type: 'چوب', image: 'images/tv7.jpg' },
    'tv8': { id: 'tv8', name: 'میز تلویزیون مدل H', type: 'چوب', image: 'images/tv8.jpg' },
    'tv9': { id: 'tv9', name: 'میز تلویزیون مدل I', type: 'چوب', image: 'images/tv9.jpg' },
    'tv10': { id: 'tv10', name: 'میز تلویزیون مدل J', type: 'چوب', image: 'images/tv10.jpg' },
    'tv11': { id: 'tv11', name: 'میز تلویزیون مدل K', type: 'چوب', image: 'images/tv11.jpg' },
    'tv12': { id: 'tv12', name: 'میز تلویزیون مدل L', type: 'چوب', image: 'images/tv12.jpg' },
    'tv13': { id: 'tv13', name: 'میز تلویزیون مدل M', type: 'چوب', image: 'images/tv13.jpg' },
    'tv14': { id: 'tv14', name: 'میز تلویزیون مدل N', type: 'چوب', image: 'images/tv14.jpg' },
    'tv15': { id: 'tv15', name: 'میز تلویزیون مدل O', type: 'چوب', image: 'images/tv15.jpg' },
    'tv16': { id: 'tv16', name: 'میز تلویزیون مدل P', type: 'چوب', image: 'images/tv16.jpg' },
    'tv17': { id: 'tv17', name: 'میز تلویزیون مدل Q', type: 'چوب', image: 'images/tv17.jpg' },
    'tv18': { id: 'tv18', name: 'میز تلویزیون مدل R', type: 'چوب', image: 'images/tv18.jpg' },
    'tv19': { id: 'tv19', name: 'میز تلویزیون مدل S', type: 'چوب', image: 'images/tv19.jpg' },
    'tv20': { id: 'tv20', name: 'میز تلویزیون مدل T', type: 'چوب', image: 'images/tv20.jpg' },
    'tv21': { id: 'tv21', name: 'میز تلویزیون مدل U', type: 'چوب', image: 'images/tv21.jpg' },

    // Jak Products (Assuming similar structure)
    'jak1': { id: 'jak1', name: 'جا کفشی کلاسیک', type: 'چوب راش - 4 طبقه', image: 'images/shoe1.jpg' },
    'jak2': { id: 'jak2', name: 'جا کفشی مدرن', type: 'چوب گردو - 3 طبقه', image: 'images/shoe2.jpg' },
    'jak3': { id: 'jak3', name: 'جا کفشی دیواری', type: 'چوب بلوط - 6 جفت', image: 'images/shoe3.jpg' },
    'jak4': { id: 'jak4', name: 'جا کفشی مینیمال', type: 'چوب کاج - 2 طبقه', image: 'images/shoe4.jpg' },
    'jak5': { id: 'jak5', name: 'جا کفشی لوکس', type: 'چوب ماهگونی - 5 طبقه', image: 'images/shoe5.jpg' },
    'jak6': { id: 'jak6', name: 'جا کفشی کودک', type: 'چوب توت - طرح کارتونی', image: 'images/shoe6.jpg' },
    'jak7': { id: 'jak7', name: 'جا کفشی جدید ۱', type: 'چوب', image: 'images/shoe7.jpg' },
    'jak8': { id: 'jak8', name: 'جا کفشی جدید ۲', type: 'چوب', image: 'images/shoe8.jpg' },
    'jak9': { id: 'jak9', name: 'جا کفشی جدید ۳', type: 'چوب', image: 'images/shoe9.jpg' },
    'jak10': { id: 'jak10', name: 'جا کفشی جدید ۴', type: 'چوب', image: 'images/shoe10.jpg' },
    'jak11': { id: 'jak11', name: 'جا کفشی جدید ۵', type: 'چوب', image: 'images/shoe11.jpg' },
    'jak12': { id: 'jak12', name: 'جا کفشی جدید ۶', type: 'چوب', image: 'images/shoe12.jpg' },
    'jak13': { id: 'jak13', name: 'جا کفشی جدید ۷', type: 'چوب', image: 'images/shoe13.jpg' },
    'jak14': { id: 'jak14', name: 'جا کفشی جدید ۸', type: 'چوب', image: 'images/shoe14.jpg' },
    'jak15': { id: 'jak15', name: 'جا کفشی جدید ۹', type: 'چوب', image: 'images/shoe15.jpg' },
    'jak16': { id: 'jak16', name: 'جا کفشی جدید ۱۰', type: 'چوب', image: 'images/shoe16.jpg' },
    'jak17': { id: 'jak17', name: 'جا کفشی جدید ۱۱', type: 'چوب', image: 'images/shoe17.jpg' },
    'jak18': { id: 'jak18', name: 'جا کفشی جدید ۱۲', type: 'چوب', image: 'images/shoe18.jpg' },
    'jak19': { id: 'jak19', name: 'جا کفشی جدید ۱۳', type: 'چوب', image: 'images/shoe19.jpg' },
    'jak20': { id: 'jak20', name: 'جا کفشی جدید ۱۴', type: 'چوب', image: 'images/shoe20.jpg' },
    'jak21': { id: 'jak21', name: 'جا کفشی جدید ۱۵', type: 'چوب', image: 'images/shoe21.jpg' },
    
    'sofa1': { id: 'sofa1', name: 'مبل راحتی مدل A', type: 'پارچه کتان', image: 'images/sofa1.jpg' },
    'sofa2': { id: 'sofa2', name: 'مبل راحتی مدل B', type: 'پارچه مخمل', image: 'images/sofa2.jpg' },
    'sofa3': { id: 'sofa3', name: 'مبل راحتی مدل C', type: 'چرم', image: 'images/sofa3.jpg' },
    'sofa4': { id: 'sofa4', name: 'مبل راحتی مدل D', type: 'پارچه مازراتی', image: 'images/sofa4.jpg' },
    'sofa5': { id: 'sofa5', name: 'مبل راحتی مدل E', type: 'پارچه شانل', image: 'images/sofa5.jpg' },
    'sofa6': { id: 'sofa6', name: 'مبل راحتی مدل F', type: 'پارچه نانو', image: 'images/sofa6.jpg' },
    // Add other products from other pages here...
    'tablo1': { id: 'tablo1', name: 'تابلو مدرن', type: 'رنگ روغن', image: 'images/tablo1.jpg' },
    'tablo2': { id: 'tablo2', name: 'تابلو کلاسیک', type: 'آبرنگ', image: 'images/tablo2.jpg' },
    'tablo3': { id: 'tablo3', name: 'اکسسوری دکوری', type: 'فلزی', image: 'images/tablo3.jpg' },

    // Bar Products
    'bar1': { id: 'bar1', name: 'بار قهوه مدل A', type: 'چوب راش', image: 'images/bar1.jpg' },
    'bar2': { id: 'bar2', name: 'بار قهوه مدل B', type: 'چوب گردو', image: 'images/bar2.jpg' },
    'bar3': { id: 'bar3', name: 'بار قهوه مدل C', type: 'چوب بلوط', image: 'images/bar3.jpg' },
};